const productx = [
  {
    id: 0,
    name: "Summer T-shirt 1",
    price: 50.99,
    instock: 10,
    imgSrc: "./slider1/t1.png",
  },
  {
    id: 1,
    name: "Summer T-shirt 2",
    price: 50.99,
    instock: 10,
    imgSrc: "./slider1/t2.png",
  },
  {
    id: 2,
    name: "Summer T-shirt 3",
    price: 50.99,
    instock: 10,
    imgSrc: "./slider1/t3.png",
  },
  {
    id: 3,
    name: "Summer T-shirt 4",
    price: 10.99,
    instock: 10,
    imgSrc: "./slider1/t4.png",
  },
  {
    id: 4,
    name: "Summer T-shirt 5",
    price: 40.99,
    instock: 10,
    imgSrc: "./slider1/t5.png",
  },
  {
    id: 5,
    name: "Summer T-shirt 6",
    price: 30.99,
    instock: 10,
    imgSrc: "./slider1/t6.png",
  },
  {
    id: 6,
    name: "Summer T-shirt 7",
    price: 25.99,
    instock: 10,
    imgSrc: "./slider1/t7.png",
  },
  
  {
    id: 7,
    name: "T-shirt 1",
    price: 29.99,
    instock: 10,
    imgSrc: "./slider2/n1.png",
  },
  {
    id: 8,
    name: "T-shirt 2",
    price: 24.99,
    instock: 13,
      imgSrc: "./slider2/n2.png",
  },
  {
    id: 9,
    name: "T-shirt 3",
    price: 19.99,
    instock: 10,
      imgSrc: "./slider2/n3.png",
  },
  {
    id: 10,
    name: "T-shirt 4",
    price: 25.99,
    instock: 5,
      imgSrc: "./slider2/n4.png",
  },
  {
    id: 11,
    name: "T-shirt 5",
    price: 29.99,
    instock: 4,
      imgSrc: "./slider2/n5.png",
  },
  {
    id: 12,
    name: "T-shirt 6",
    price: 39.99,
    instock: 10,
      imgSrc: "./slider2/n6.png",
  },
  {
    id: 13,
    name: "Short 1",
    price: 39.99,
    instock: 20,
      imgSrc: "./slider2/n7.png",
  },
  
];
